"""Security headers middleware.

Adds a small set of defensive response headers on every response. Intended to
be the OUTERMOST middleware so the headers wrap all responses (including ones
generated by other middlewares such as CORS). In Starlette, middleware added
LAST runs OUTERMOST (it wraps everything added before it). So in main.py we
add CORS first, then this — meaning this runs outermost.
"""
from __future__ import annotations

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response


_HEADERS = {
    "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
    "X-Frame-Options": "DENY",
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Permissions-Policy": "geolocation=(), microphone=(), camera=()",
}


class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next) -> Response:
        response = await call_next(request)
        for name, value in _HEADERS.items():
            # Don't clobber if a route already set its own value
            response.headers.setdefault(name, value)
        return response


__all__ = ["SecurityHeadersMiddleware"]
